CREATE TABLE [dbo].[Coin](
	[Id] [bigint] IDENTITY(100000,1) NOT NULL,
	[Denomination] [int] NOT NULL,
	[Count] [int] NOT NULL,
	[Lock] [bit] NOT NULL,
 CONSTRAINT [PK_Coin] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[Drink](
	[Id] [bigint] IDENTITY(100000,1) NOT NULL,
	[Cost] [decimal](18, 2) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
	[Ord] [int] NOT NULL,
 CONSTRAINT [PK_Drink] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

CREATE TABLE [dbo].[DrinkBalance](
	[Id] [bigint] IDENTITY(100000,1) NOT NULL,
	[DrinkId] [bigint] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_DrinkBalance] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PaymentCoin](
	[Id] [bigint] IDENTITY(100000,1) NOT NULL,
	[CoinId] [bigint] NOT NULL,
	[Count] [int] NOT NULL,
 CONSTRAINT [PK_PaymentCoin] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[SelectedDrink](
	[Id] [bigint] IDENTITY(100000,1) NOT NULL,
	[DrinkId] [bigint] NOT NULL,
 CONSTRAINT [PK_SelectedDrink] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET IDENTITY_INSERT [dbo].[Coin] ON 
INSERT [dbo].[Coin] ([Id], [Denomination], [Count], [Lock]) VALUES (100000, 1, 20, 0)
INSERT [dbo].[Coin] ([Id], [Denomination], [Count], [Lock]) VALUES (100001, 2, 20, 0)
INSERT [dbo].[Coin] ([Id], [Denomination], [Count], [Lock]) VALUES (100002, 5, 20, 0)
INSERT [dbo].[Coin] ([Id], [Denomination], [Count], [Lock]) VALUES (100003, 10, 20, 0)
SET IDENTITY_INSERT [dbo].[Coin] OFF

CREATE UNIQUE NONCLUSTERED INDEX [IX_DrinkBalance_DrinkId] ON [dbo].[DrinkBalance]
(
	[DrinkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [IX_PaymentCoin_CoinId] ON [dbo].[PaymentCoin]
(
	[CoinId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [IX_SelectedDrink_DrinkId] ON [dbo].[SelectedDrink]
(
	[DrinkId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE [dbo].[Coin] ADD  CONSTRAINT [DF_Coin_Denomination]  DEFAULT ((1)) FOR [Denomination]

ALTER TABLE [dbo].[Coin] ADD  CONSTRAINT [DF_Coin_Count]  DEFAULT ((0)) FOR [Count]

ALTER TABLE [dbo].[Coin] ADD  CONSTRAINT [DF_Coin_Lock]  DEFAULT ((0)) FOR [Lock]

ALTER TABLE [dbo].[Drink] ADD  CONSTRAINT [DF_Drink_Cost]  DEFAULT ((0)) FOR [Cost]

ALTER TABLE [dbo].[Drink] ADD  CONSTRAINT [DF_Drink_Ord]  DEFAULT ((0)) FOR [Ord]

ALTER TABLE [dbo].[DrinkBalance] ADD  CONSTRAINT [DF_DrinkBalance_Count]  DEFAULT ((1)) FOR [Count]

ALTER TABLE [dbo].[PaymentCoin] ADD  CONSTRAINT [DF_PaymentCoin_Count]  DEFAULT ((1)) FOR [Count]

ALTER TABLE [dbo].[DrinkBalance]  WITH CHECK ADD  CONSTRAINT [FK_DrinkBalance_Drink] FOREIGN KEY([DrinkId])
REFERENCES [dbo].[Drink] ([Id])
ON DELETE CASCADE

ALTER TABLE [dbo].[DrinkBalance] CHECK CONSTRAINT [FK_DrinkBalance_Drink]

ALTER TABLE [dbo].[PaymentCoin]  WITH CHECK ADD  CONSTRAINT [FK_PaymentCoin_Coin] FOREIGN KEY([CoinId])
REFERENCES [dbo].[Coin] ([Id])
ON DELETE CASCADE

ALTER TABLE [dbo].[PaymentCoin] CHECK CONSTRAINT [FK_PaymentCoin_Coin]

ALTER TABLE [dbo].[SelectedDrink]  WITH CHECK ADD  CONSTRAINT [FK_SelectedDrink_Drink] FOREIGN KEY([DrinkId])
REFERENCES [dbo].[Drink] ([Id])
ON DELETE CASCADE

ALTER TABLE [dbo].[SelectedDrink] CHECK CONSTRAINT [FK_SelectedDrink_Drink]